### ISSUE TITLE
R&D Technique - Infra, réseaux, sécurité

### ISSUE THREAD

**Issue by jul-fls** [epsi-safe-place/backend#4]

**Comment by jul-fls** [comment]
- Déploiement via docker compose sur infra portainer (2 nodes)
- Infra 2 vms docker (vm proxmox qemu debian 12) sur cluster proxmox
- Accès frontend via cache / anti ddos cloudflare access 
- Exposition via cloudflare argo tunnel

**Comment by ianlogeais** [comment]
> * Déploiement via docker compose sur infra portainer (2 nodes)
> * Infra 2 vms docker (vm proxmox qemu debian 12) sur cluster proxmox
> * Accès frontend via cache / anti ddos cloudflare access
> * Exposition via cloudflare argo tunnel

Test d’injection sql sur la BDD PostgreSQL
Test des failles XSS dans l’application
Test DDOS (le captcha fera une protection sur ça) (cloudflare access s’occupe de ça tout seul)
Sensibilisation utilisateur basique sur mot de passe (complexité, MFA, etc…)
Gestion du TOTP via expressJS

Recommandation robustesse MDP : https://cyber.gouv.fr/sites/default/files/2021/10/anssi-guide-authentification_multifacteur_et_mots_de_passe.pdf
